### ISSUE TITLE
Lot registration for NovaSeq

### ISSUE THREAD

**Issue by fa2k** [nsc-norway/lims#11]
Available in LIMS interface:

|           Reagent |  On box label                   | In LIMS interface   |
|------------------:|---------------------------|---------------------|
|  Buffer cartridge | Buffer Cartridge (Box lot) |  Yes (cartridge lot) |
|  SBS cartridge | SBS Cartridge (Box lot) |  Yes (cartridge lot) |
|  Cluster cartridge | Cluster Cartridge (Box lot) |  Yes (cartridge lot) |
|  Xp 2 lane kit | Kit box |  no |
|  Flow cell | Flow cell box  (box lot, FCID) | Lot & FCID, As UDF not Kit |
|  Library tube | Library tube box  (Lot#, no ID) | ID as container name, not lot# |
|  DPX1 | ? | Manual registration |
|  DPX2 | ? | Manual registration |
|  DPX3 | ? | Manual registration |
|  NaOH | no | Manual registration |
|  RSB | no | Manual registration |
|  Tris-HCl | no | Manual registration |

LIMS interface

Sequencing step

![Screenshot 2019-11-26 at 15 52 19](https://user-images.githubusercontent.com/1238849/69644426-eac87080-1064-11ea-8e6a-18739c6cd48f.png)

Load to flowcell step

![Screenshot 2019-11-26 at 16 00 26](https://user-images.githubusercontent.com/1238849/69645113-eea8c280-1065-11ea-9ba1-3275cd7900a1.png)

Box images

![IMG_20191126_104552](https://user-images.githubusercontent.com/1238849/69643885-32023180-1064-11ea-9427-3f754fc20180.jpg)
![IMG_20191126_131241](https://user-images.githubusercontent.com/1238849/69643886-32023180-1064-11ea-84ad-391465f2743f.jpg)
![IMG_20191126_131249](https://user-images.githubusercontent.com/1238849/69643887-32023180-1064-11ea-8745-973facbf577f.jpg)
![IMG_20191126_131254](https://user-images.githubusercontent.com/1238849/69643889-329ac800-1064-11ea-8dae-251220a84807.jpg)
![IMG_20191126_131300](https://user-images.githubusercontent.com/1238849/69643890-329ac800-1064-11ea-963b-16782620bf8d.jpg)
![IMG_20191126_131309](https://user-images.githubusercontent.com/1238849/69643891-329ac800-1064-11ea-91e3-faa3e7c88237.jpg)
![IMG_20191126_131316](https://user-images.githubusercontent.com/1238849/69643892-33335e80-1064-11ea-88c0-b89ff29abdba.jpg)

**Comment by ghost** [comment]
Lot registration is working well for NSC and diagnostics!
