### ISSUE TITLE
FastQC Warning "Too many tiles (>500) so giving up trying to do per-tile qualities"

### ISSUE THREAD

**Issue by fa2k** [nsc-norway/lims#14]
Need to upgrade FastQC?

**Comment by fa2k** [comment]
It's fixed in FastQC 0.11.6: https://www.bioinformatics.babraham.ac.uk/projects/fastqc/

**Comment by ghost** [comment]
New FastQC is used on the novaseq-support branch ( https://github.com/nsc-norway/pipeline/commit/77f40eb80bdb58ac080ef7262f975259889e1b89 ) . The entire change may need to be validated.
