### ISSUE TITLE
Separate files per lane, or merge all lanes

### ISSUE THREAD

**Issue by fa2k** [nsc-norway/lims#6]
Setting of the "No lane splitting" option in bcl2fastq, and confirm that the pipeline handles both cases. Per now, tested with one file per lane, in Standard workflow (no lane column in sample sheet). 

For Xp workflow, need to have separate files.

Diagnostics want merged fastq files. They do want separate folders per sample, under the project, like

    191119_A0000.Project_Diag-foo-2019-11-19/Sample_0000000/.....

This is unlike the MiSeq / NextSeq case, where such folders are not created, because there is a quite limited number of files.

Tasks are to develop a preliminary logic to set the No lane splitting, and to validate the workflow with this option.

**Comment by fa2k** [comment]
Current solution: Detect Xp workflow or Standard workflow based on the container type. Set No Lane Splitting for standard workflow. The only open question is if we want No Lane Splitting or not for NSC runs.

**Comment by ghost** [comment]
The current solution will do, and we can change later if necessary
